### PR TITLE
Add PythonEditor component

### PR DESCRIPTION
**Pull request by sahircansurmeli**
Added PythonEditor component. I have tested it with all of the lab assignments of the first year Python course from a.y. 2020/2021, and everything seems to be working well.

Since it uses abstract syntax trees to parse the code and await inputs, there might be some rare shortcomings where the function is assigned to a different variable and called from there.

For example the following code runs without any problems:
```py
def get_name():
    return input("Your name: ")

get_name()
```

However the following doesn't run:
```py
def get_name():
    return input("Your name: ")

x = get_name
x() 
```

### CODE REVIEW

**Comment by sahircansurmeli** [comment]
Link to the repo of the component: [https://github.com/sahircansurmeli/python-editor](url)

**Review by e-caste — CHANGES_REQUESTED** [review]
This already looks great, awesome job! I've played with it for a bit and I have a few notes and questions/requests:
#### Stuff I like
- the syntax highlighting works quite well
- the fact that the return key auto-indents the code at the indent point of the previous line is very handy
- the raised exceptions box looks nice!
#### Stuff I have some questions about
- the file selection is a bit unexpected: when I click on `+` I would expect another file tab to open, but instead you have used a `<select>` (not very important, but if you could separate the open files in different tabs it would look a bit better imo)
- I don't understand how to install a new package: I've looked at the [PyOdide micropip docs](https://pyodide.org/en/stable/usage/api/micropip-api.html) and an `import micropip; await micropip.install("numpy")` should work, but if I try it it raises a ModuleNotFoundException for micropip
#### Stuff I would change
- the "Close" button near the output has no way to bring it back, once the output is deleted it's gone. What if I have run a very long script and I click it by mistake? I would use a collapsible component that hides the output but can show it back

**Comment by sahircansurmeli** [comment]
- Uses tabs instead of a select component
- Removed the "Close" button from the output altogether
- Installed micropip so the packages might be installed in the following way:
```py
import micropip
await micropip.install("numpy")

import numpy

print(numpy.e)
```

**Review by e-caste — CHANGES_REQUESTED** [review]
Very nice! 

The files opened in the tab can't be deleted with a button, but an `import os; os.remove("file")` works and the tab containing that file automatically closes (even if the deletion is invoked from the same file, which is nice).

At this point I'd say that the final step before merging it to master is to add some help for the user (also a fullscreen editor view? Read at the end). You could either add a button which explains how to use this, or set up the initial contents of the main.py file with an example such as:
```py
import micropip
# to install other libraries, simply copy the next line and replace numpy with the name of the library you want to install
await micropip.install("numpy")

# set up your imports here, below the libraries installation steps
import numpy as np
# these are included in the Python standard library, and do not need an installation step:
import json  
from sys import version

# at this point, you can run any standard Python code and the code from the libraries you have installed
x = np.arange(0.0, 2.0, 0.01)
y = 1 + np.sin(2 * np.pi * x)

# you can even interact with a virtual filesystem entirely inside your browser! 
# (be careful to copy these files locally if you want to preserve their contents, once you reload the page they are lost)
file_name = "protagonists.json"
protagonists = {
    'Better Caul Saul': ["Saul Goodman", "Kim Wexler"],
    'The Office': ["Michael Scott", "Dwight Schrute", "Jim Halpert", "Pam Beesly"],
    'Severance': ["Mark", "Helly", "Mr. Milchick", "Ms. Cobel"]
}
with open(file_name, "w") as f:
    json.dump(protagonists, f, indent=4)
# you will also notice that a tab has been opened with the newly created file
# you can remove it if you wish with: import os; os.remove(file_name)
# after writing to file, we can read it to a different variable name
file_contents = json.load(open(file_name, "r"))

num_separators = 42
print(f"Sine wave y values:\n{y}")
print("∿" * num_separators * 2)
print(f"Contents of {file_name}:\n{file_contents}")
print("🐍" * num_separators)
print(f"This is running completely inside your browser using Python version {version.split(' ')[0]}!")
```

For the future, I think it would be nice to enable `matplotlib` support to show graphs in the output cell, add better code suggestions based on the actual methods and classes available, and maybe a dark mode.  

For skeeelled, we will need a way to automatically copy data at the press of a button from the code editor into the text input of the comment and a full screen view for the code editor (maybe this can already be implemented now?).

**Comment by sahircansurmeli** [comment]
- Default files can be passed by props
- Tabs can be now closed. Closing a tab deletes the file from the filesystem. Default files cannot be closed.
- Added full screen
- Added dark mode
- Added copy functionality. Copying an already copied .py file replaces the previously copied code block. This feature does not apply to files with other file extensions.

**Review by e-caste — CHANGES_REQUESTED** [review]
Very nice looking editor page! I like the multiple files copy!  
A couple of things to fix:
- in fullscreen mode the bottom half of the vertical viewport is wasted
Screenshot 2022-09-13 at 15 15 56
- in fullscreen mode, if I create or delete a file the fullscreen mode is closed

**Review by e-caste — APPROVED** [review]

**Pull request merged**
